[gcp]
bucket_name = "competencies-wcs"
service_account_json = """
{
  "type": "service_account",
  "project_id": "big-icon-194115",
  "private_key_id": "26477e607e87xxxxxxxxxxxxxxxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIE...your full key here...==\n-----END PRIVATE KEY-----\n",
  "client_email": "big-icon-194115@big-icon-194115.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/big-icon-194115%40big-icon-194115.iam.gserviceaccount.com"
}
"""
